### PR TITLE
Fix for leaderboard photos not updating

### LINKED ISSUE #416: Bug: Updating Leaderboard photos doesn't work
When editing the top three leaderboard photos, we are not saving the values into the DB. 

It looks like we are still trying to look for and update a `user_id` column and everything has been updated to use `northstar_id` 

https://github.com/DoSomething/gladiator/blob/master/app/Http/Controllers/CompetitionsController.php#L290-L318

### PR DESCRIPTION
**Pull request by sbsmith86**
#### What's this PR do?

Uses `northstar_id` instead of `user_id` to find the Leaderboard photo to update and to store in the DB. 

#### How should this be manually tested?

👀 

#### What are the relevant tickets?
Fixes #416

### CODE REVIEW

File: app/Http/Controllers/CompetitionsController.php [hunk 1]
```diff
@@ -290,21 +290,21 @@ public function editLeaderboardPhotos(Competition $competition, Message $message
...
             //                 reportback_id_{{$index}}, reportback_item_id_{{$index}}
-            $userId = $request->input('user_id_'.$i);
+            $northstarId = $request->input('northstar_id_'.$i);
             $reportbackId = $request->input('reportback_id_'.$i);
             $reportbackItemId = $request->input('reportback_item_id_'.$i);
 
             // If none of ids null
-            if (($userId != 0) && ($reportbackId != 0) && ($reportbackItemId != 0)) {
-                $photo = LeaderboardPhoto::where('competition_id', '=', $competition->id)->where('message_id', '=', $message->id)->where('user_id', '=', $userId)->first();
+            if (($northstarId != 0) && ($reportbackId != 0) && ($reportbackItemId != 0)) {
```
Comment (DFurnes) [inline app/Http/Controllers/CompetitionsController.php]: This check can probably be removed, since Northstar doesn't have a `0` anonymous user like Drupal.

Comment (DFurnes) [inline app/Http/Controllers/CompetitionsController.php]: Oh unless this is a null check? If so, could we just check truthiness or explicitly against `is_null`?

Comment (sbsmith86) [inline app/Http/Controllers/CompetitionsController.php]: @DFurnes ah yea i think it is a null check because it is a form request we are sending over, so we are making sure it was sent.

Comment (DFurnes) [inline app/Http/Controllers/CompetitionsController.php]: Hmm yeah, okay! I'm fine with merging as-is.
