### PR TITLE
Updates to fix showing User activity on single user show page.

### LINKED ISSUE #227: Fix call to missing function
image

Function was removed in #224. Missed additional call to it in a different function.

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?
This PR fixes an error with a missing function call that was introduced after #224 was merged. This cleans up and fixes that issue using a similar approach as some of the other methods in the `Manager` class. It also adds a few helpful helper functions.

#### How should this be manually tested?
Load a competition with users, click on a user to view their individual page, and see if their user activity is displayed for the competition with Reportbacks (if any), etc.

#### What are the relevant tickets?
Fixes #227

---
@DoSomething/gladiator

### CODE REVIEW

File: app/Http/Controllers/UsersController.php [hunk 1]
```diff
@@ -97,20 +97,20 @@ public function store(UserRequest $request)
...
-        // Get the user's reportback for each competition they are in.
         foreach ($competitions as $competition) {
-            $reportback = $this->manager->getActivityForUser($id, $competition);
+            $parameters = $this->manager->getCampaignParameters($competition);
+            $parameters['users'] = $user->id;
 
-            if ($reportback) {
-                $competition->reportback = $reportback;
-            }
+            $activities[] = $this->manager->appendReportback($competition, $parameters);
```
Comment (weerd) [inline app/Http/Controllers/UsersController.php]: Ended up saving the updated competition to the activities array, but could potentially just be reduced to override the competition in the collection? Thoughts?

File: resources/views/users/show.blade.php [hunk 2]
```diff
@@ -1,3 +1,5 @@
+{{-- dd($activities) --}}
```
Comment (sbsmith86) [inline resources/views/users/show.blade.php]: should this be removed?

File: app/helpers.php [hunk 3]
```diff
@@ -73,6 +73,17 @@ function format_date_form_field($model, $field, $defaut = 'MM/DD/YYYY')
 }
 
 /**
+ * Formate a timestamp using Carbon for display in a view.
+ *
+ * @param  string  $timestamp
+ * @return /Carbon/Carbon
+ */
+function format_timestamp_for_display($timestamp)
```
Comment (sbsmith86) [inline app/helpers.php]: You end up using this function on the `updated_at` field which is already a `Carbon` instance (at least, it should be) and then in this function you make a new Carbon instance out of it again. Is that on purpose?

File: resources/views/users/show.blade.php [hunk 4]
```diff
@@ -38,12 +40,11 @@
                             <th class="table__cell">Items</th>
                             <th class="table__cell">Quantity</th>
                             <th class="table__cell">Updated At</th>
-                            <th class="table__cell">Flagged</th>
```
Comment (sbsmith86) [inline resources/views/users/show.blade.php]: we don't need this anymore?

File: resources/views/users/show.blade.php [hunk 5]
```diff
@@ -55,20 +56,20 @@
...
-                                <td class="table__cell">{{ $competition->reportback->flagged or 'N/A' }}</td>
-                                <td class="table__cell"><a href="{{ route('competitions.users.destroy', ['user' => $user->id, 'competition' =>$competition->id]) }}" class="button -danger">Remove</a></td>
+
+                                @if ($competition->reportback)
+                                    <td class="table__cell"><a href="{{ reportback_admin_url($competition->reportback->id) }}">{{ $competition->reportback->id }}</a></td>
+                                    <td class="table__cell">{{ $competition->reportback->reportback_items->total }}</td>
+                                    <td class="table__cell">{{ $competition->reportback->quantity }}</td>
+                                    <td class="table__cell">{{ format_timestamp_for_display($competition->reportback->updated_at) }}</td>
+                                @else
+                                    <td class="table__cell">N/A</td>
```
Comment (sbsmith86) [inline resources/views/users/show.blade.php]: Why can't you use the `or` operator here anymore?

File: resources/views/users/show.blade.php (hunk 2 above)
Comment (weerd) [inline resources/views/users/show.blade.php]: doh!

File: app/helpers.php (hunk 3 above)
Comment (weerd) [inline app/helpers.php]: It's not a Carbon instance when retrieved. It's the Reportback data coming from Phoenix, which is just a straight-up regular object.

File: resources/views/users/show.blade.php (hunk 4 above)
Comment (weerd) [inline resources/views/users/show.blade.php]: I didn't think so. Especially since what we actually care about is the statuses of the RB items, not the Reportback parent object.

File: resources/views/users/show.blade.php (hunk 5 above)
Comment (weerd) [inline resources/views/users/show.blade.php]: Not really because it needs to check for nested properties of the reportback object if the `$competition->reportback` object exists. There's no way to easily use `or` if it's not the direct item you're looking for.

So say if I did this:
```php
$competition->reportback->quantity or 'NA'
```

If `$competition->reportback` was `null` to begin with I believe it would fail cause then it's trying to get a `quantity` property on `null`.

File: resources/views/users/show.blade.php (hunk 4 above)
Comment (weerd) [inline resources/views/users/show.blade.php]: But I could defs be wrong! @mikefantini do we _need_ the RB flagged stuff in this table view?

File: resources/views/users/show.blade.php (hunk 5 above)
Comment (weerd) [inline resources/views/users/show.blade.php]: It's also cause now I'm just appending the Reportback to the competition. If there isn't any, it's `null`. Wanted to go about using similar approaches w/ how RBs are appended to collection of users, single user, or competition.

File: app/helpers.php (hunk 3 above)
Comment (sbsmith86) [inline app/helpers.php]: oh ok. i see.

File: resources/views/users/show.blade.php (hunk 5 above)
Comment (sbsmith86) [inline resources/views/users/show.blade.php]: got it.

**Comment by sbsmith86** [comment]
looks good to me 👍

**Comment by weerd** [comment]
thanks @sbsmith86 💃
