### PR TITLE
Welcome message bug

### LINKED ISSUE #323: Welcome email bug
Welcome emails are not sending with customized content.

### PR DESCRIPTION
**Pull request by sbsmith86**
#### What's this PR do?
I found two problems.

1) Welcome test messages were f**ked cause we weren't passing in the contest explicity and it was causing errors when trying to grab information about the contest in the `Email` class.

2) Welcome emails were f**ked cause we pass in a `$params` array that we use to query the `Message` table but we were just looking for the first email of type welcome with key 0...

We probably didn't notice cause mostly all the welcome emails were the same..but if you updated one for a specific contest, we didn't care. 

#### How should this be manually tested?

Go to a contest, customize the welcome message.

Post to `/users` and you should get a welcome email with the right content. 

also go ahead and send yourself a test email. that should work as well. 

#### Any background context you want to provide?

giphy 1

#### What are the relevant tickets?

Fixes #323

### CODE REVIEW

**Comment by angaither** [comment]
@sbsmith86 nothing additional needs to be POSTed to the `/users` endpoint, correct? 
> Post to /users and you should get a welcome email with the right content.

**Comment by sbsmith86** [comment]
@angaither ah nah you have to post some data: 

```
{ 
   "id"   : "INSERT_YOUR_EMAIL",
   "term" : "email",
   "campaign_id"   : CAMPAIGN_ID,
   "campaign_run_id" : RUN_ID
}
```

**Comment by sbsmith86** [comment]
@angaither here is postman link to the collection i set up https://www.getpostman.com/collections/473d2791284c5e5b599f

**Comment by angaither** [comment]
@sbsmith86 right right, but the data we have to post is the same as it was before. (just want to make sure nothing has to change on the Phoenix end)

**Comment by sbsmith86** [comment]
@angaither oh ya that's all the same.

**Comment by angaither** [comment]
I'm probably being super dense here, but where do you select the correct message with the correct contest id?

**Comment by sbsmith86** [comment]
@angaithe no worries! 

[here](https://github.com/DoSomething/gladiator/pull/324/files?diff=split#diff-ee610ebae812c24f376dea1ff2170273R102) we set a `$params` array which we pass to as `sendEmail` function. 

[that function uses $params to grab the correct message](https://github.com/DoSomething/gladiator/blob/master/app/Services/Manager.php#L519)

**Comment by angaither** [comment]
ah the ol' `where::($params)` of course 👍 


🚢 🚀 💌

File: app/Http/Controllers/MessagesController.php [hunk 1]
```diff
@@ -92,7 +92,9 @@ public function sendMessage(Message $message)
     {
         // Get competition with activity.
         $competitionId = request('competition_id');
-        // $competition = null;
+
+        $contest = Contest::find(request('contest_id'));
+        $this->manager->appendCampaign($contest);
```
Comment (weerd) [inline app/Http/Controllers/MessagesController.php]: do you need to resave `$contest` here?

```php
$contest = $this->manager->appendCampaign($contest);
```

Comment (sbsmith86) [inline app/Http/Controllers/MessagesController.php]: not sure i know what you mean by resave? i need to append the campaign info...

Comment (weerd) [inline app/Http/Controllers/MessagesController.php]: it appends it sure, but it doesn't get actually added to the `$contest` unless you reassign `$contest` to the return value from `$this->manager->appendCampaign($contest);`

Comment (weerd) [inline app/Http/Controllers/MessagesController.php]: For example here: https://github.com/DoSomething/gladiator/blob/a924244398fe05108a1009867c04c9f3181f41f4/app/Http/Controllers/ContestsController.php#L86

Comment (weerd) [inline app/Http/Controllers/MessagesController.php]: Otherwise you're still passing along the original `$contest` data w/out the Campaign info attached.

Comment (sbsmith86) [inline app/Http/Controllers/MessagesController.php]: yea that is probably safer...but it actually works /shrug

I was following what was done here: 

https://github.com/DoSomething/gladiator/blob/f4fda9c508118e9051a60c532bf5d7041d7487a1/app/Http/Controllers/Api/UsersController.php#L96

I will update though.

Comment (sbsmith86) [inline app/Http/Controllers/MessagesController.php]: @weerd updated!

Comment (weerd) [inline app/Http/Controllers/MessagesController.php]: Shit. I think it's done incorrectly there too @_@ I don't know how that is working correctly...

Comment (sbsmith86) [inline app/Http/Controllers/MessagesController.php]: lemme just fix that while im here

**Comment by weerd** [comment]
:sheep: it!
