### PR TITLE
Leaderboard bug

### LINKED ISSUE #392: BUG: Leaderboard showing n/a for all constestants
### Current Behavior

Competitions are showing `n/a` for all values and contestants:

Seems to be happening on only some competitions, For example: 

http://gladiator.dosomething.org/competitions/245/leaderboard

screen shot 2017-04-10 at 9 39 36 am

### Expected behavior

This should pull in activity for the users.

### PR DESCRIPTION
**Pull request by sbsmith86**
#### What's this PR do?

Now that we are getting user activity directly from phoenix, the data gets returned to us with embedded arrays instead of objects. This changes how we pull in the data to the leaderboard view and the leaderboard export. 

This PR updates the code so that we pull in the data accessing the arrays, instead of trying to use objects. 

#### How should this be manually tested?

* Go to a leaderboard and you should see the data in the view instead of `N/A`.
* Try to export a leaderboard and it should export properly without throwing errors that you are trying to get a property of a non-object. 

#### What are the relevant tickets?
Fixes #392

### CODE REVIEW

File: app/Services/Manager.php [hunk 1]
```diff
@@ -116,7 +116,7 @@ public function getStatus($data, $status)
         $list = [];
 
         foreach ($data as $reportbackitem) {
-            if ($reportbackitem->status == $status) {
+            if ($reportbackitem['status'] == $status) {
```
Comment (weerd) [inline app/Services/Manager.php]: Can we update this to `===`? :)

Comment (sbsmith86) [inline app/Services/Manager.php]: word.
